package org.Q51to58;

public class Q52 {
    /**
     52- Write a method that returns the sum of all even Fibonacci numbers.
     Consider all Fibonacci numbers that are less than or equal to n.
     Each new element in the Fibonacci sequence is generated by adding the previous two elements.
     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...*/

    public int Fibonacci(int n) {
         int sum = 0;
         int a = 1, b = 1;
         while (b <= n) {
              if (b % 2 == 0) {
                   sum += b;
              }
              int temp = a + b;
              a = b;
              b = temp;
         }
         return sum;
    }

     public static void main(String[] args) {
          Q52 q52=new Q52();
          System.out.println(q52.Fibonacci(30));
     }

     }
